name: Update Version

on:
  release:
    types:
      - created

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update version
        run: |
          npm version ${{ github.event.release.tag_name }}
          git push --follow-tags
